# DO NOT EDIT THIS FILE!! 
# IF MODIFIED IN ANY WAY, YOU WILL RECEIVE 0 FOR THE GRADE!
import math
# Function 1 (30): Convert the given polar coordinates (r,θ) to Cartesian coordinates (x,y). 
# This function should take the polar coordinates (r,θ) and return Cartesian coordinates (x,y).
def polar_to_cartesian(r, theta):
    angle_radians = math.radians(theta)
    x = round(r*math.cos(angle_radians),5)
    y = round(r*math.sin(angle_radians),5)
    return (x, y)
r = float(input("Enter r coordinate:"))
theta = float(input("Enter theta:"))
print(f"{polar_to_cartesian(r, theta)}")

# Function 2(30): Convert Cartesian coordinates (x,y) to polar coordinates (r,θ).
# This function should take the Cartesian coordinates (x,y) as input and return the polar coordinates (r,θ).
def cartesian_to_polar(x, y):
    angle_radians = math.radians(theta)
    r = round(math.sqrt(x**2 + y**2),5)
    theta = round(math.atan(x/y),5)
    return (r, angle_radians)
x = float(input("Enter x coordinate:"))
y = float(input("Enter y coordinate:"))
print(f"{cartesian_to_polar(x,y)}")

# Function 3 (40): Calculate the position of pendulum for (A, f, ϕ, t).
# This function should take (A, f, ϕ, t) as input and return the position value x.
def pendulum_position(A, f, phi, t):
    omega = 2*math.pi*f
    angle_radians = math.radians(phi)
    position = A*math.cos(omega*t + angle_radians)
    return position
A = float(input("Enter amplitude:"))
f = float(input("Enter frequency:"))
phi = float(input("Enter phi:"))
t = float(input("Enter time:"))
print(f"{pendulum_position(A, f, phi, t)}")